export { default as MovieBackdrop } from './MovieBackdrop';
export { default as MovieCard } from './MovieCard';
export { default as MovieCast } from './MovieCast';
export { default as MovieDetails } from './MovieDetails';
export { default as MovieList } from './MovieList';
export { default as MovieOverview } from './MovieOverview';
export { default as MoviePoster } from './MoviePoster';
export { default as MovieReviews } from './MovieReviews';
export { default as SimilarMovies } from './SimilarMovies';
